### PR TITLE
Added navroute event

### PR DESCRIPTION
**Pull request by spansh**
In order to better gather data about the galaxy (system body counts and navroutes) I propose adding the following to EDDN

### CODE REVIEW

**Comment by spansh** [comment]
Sample navroute
```json {"$schemaRef": "https://eddn.edcd.io/schemas/journal/1", "header": {"gatewayTimestamp": "2019-07-11T23:59:41.983688Z", "softwareName": "EDSM", "softwareVersion": "1.0.1", "uploaderID": "37065b332986f097147700a4f35c31bf98754306"}, "message": { "timestamp":"2020-04-27T08:02:52Z", "event":"Route", "Route":[
{ "StarSystem":"i Bootis", "SystemAddress":1281787693419, "StarPos":[-22.37500,34.84375,4.00000], "StarClass":"G" }, { "StarSystem":"Acihaut", "SystemAddress":11665802405289, "StarPos":[-18.50000,25.28125,-4.00000], "StarClass":"M" }, { "StarSystem":"LHS 455", "SystemAddress":3686969379179, "StarPos":[-16.90625,10.21875,-3.43750], "StarClass":"DQ" }, { "StarSystem":"SPF-LF 1", "SystemAddress":22661187052961, "StarPos":[2.90625,6.31250,-9.56250], "StarClass":"M" }, { "StarSystem":"Luyten's Star", "SystemAddress":7268024264097, "StarPos":[6.56250,2.34375,-10.25000], "StarClass":"M" }] }}```

**Comment by bgol** [comment]
Why is the navroute schema at version v3.0?
And the example above does have the wrong schema :)

**Comment by spansh** [comment]
> Why is the navroute schema at version v3.0?
> And the example above does have the wrong schema :)

I forgot to change the schema link in the example will do now.  The version is a 3.0 as I mistakenly thought the version numbers were against game versions, not simply incrementing, I can switch it to 1 if they're not

**Comment by bgol** [comment]
> The version is a 3.0 as I mistakenly thought the version numbers were against game versions, not simply incrementing, I can switch it to 1 if they're not

Each schema started with version 1. There only was a version increment if the change was major (like a new required field, which would break all sender).

**Comment by spansh** [comment]
It's been pointed out Progress is personal data, so I'm going to add a strip for that

**Comment by Athanasius** [comment]
Now that this is only for NavRoute, and in its own schema, I don't see anything else that needs changing.

**Pull request merged**
