### PR TITLE
Point to the EDDN Rust crate

### PR DESCRIPTION
**Pull request by nixpulvis**
~It's not published to crates.io yet, but that's something I plan to do soon.~ I've pushed some per-releases to crates.io. For the sake of an example, the source shows how to setup ZMQ and the needed decompression and parsing calls. Since this is what I'm actually using for my project, the referenced `elite_journal` crate is still a bit of a work in progress, and goes well above and beyond what I would call an "example".

If you'd like I could just copy out the most relevant code into a small `main.rs` without any complex parsing. Leaving a smaller note about this crate.

### CODE REVIEW

**Comment by Athanasius** [comment]
Perhaps something a little more verbose than just "Use <url>".

Also the pointed-to repo could use a README.md.

**Comment by Athanasius** [comment]
Ping @nixpulvis - any chance of addressing my comments above ?  If I get no response in a month or so I'll just close this.

**Comment by nixpulvis** [comment]
Sorry, my life's been a bit busy lately and I haven't had time to play E:D and as such I've somewhat put development of these crates on hold. That being said they are still in good shape, so I'll try to find time before next week to add a nice little README so we can close this out properly.

Thanks for the ping.

**Comment by nixpulvis** [comment]
OK, unless someone knows a way to continue a PR from a deleted branch, I think this one is going to have to be dead in the water.

I've created a new fork over here: https://github.com/nixpulvis/EDCD-EDDN, which I'll probably wait a bit before pushing back upstream here until I have [elite_journal](https://github.com/nixpulvis/elite_journal) polished a bit more. I realized I had stuff in my stash that was going to add some more event types and change the structure a bit.

Anyway, my original goal was to have a fast and well documented API, so far I'm really only maybe two thirds of the way there so far.

Sorry for the premature pull request.

**Pull request closed without merging**
