### PR TITLE
"/beta" and "/live" endpoint

### PR DESCRIPTION
**Pull request by bgol**
Added an '/beta' endpoint to all current schemas for data of an ongoing beta version of elite.

### CODE REVIEW

**Comment by AnthorNet** [comment]
This might not be retro-compatible with listener just checking for test part in schema?

**Comment by bgol** [comment]
But which listener does only listen to test and expects beta data? I think a clear distinction between actual `beta` data and just a simple `test` message outweigh a maybe break in old software.

Also a `test` message may be syntactical correct but the content might not be.

**Comment by AnthorNet** [comment]
I was actually thinking about the reverse.. :D
Listener that just check for "test" in schema header to reject them, before any other proceedings.

I'm not against it, but repercussions needs to be checked.
At least on the big three, and may be wait after the actual beta not to screw anyone, and it's in place or next beta.

This will also need to readme edit and wiki? Need to check once at the office!

**Comment by bgol** [comment]
Listeners should normaly reject it with some sort of 'schema unkown' otherwise the listener is severely broken anyway.

 The readme is just a link to the wiki and I don't know how to include the wiki into a pull request (I would have done it otherwise). Is that even possible?

**Comment by SayakMukhopadhyay** [comment]
Why not bump the version of the schema? I have heard of people asking for a schema bumping in the EDCD server a few times now. This will also let people migrate over slowly. I like the idea of having a `beta` endpoint separate from the `test` endpoint.

**Comment by bgol** [comment]
It's just a new endpoint, no schema change is done in itself, so no version bump.

**Comment by SayakMukhopadhyay** [comment]
Yeah, but I understand why this could break existing stuff. If someone is filtering out the test endpoint instead of listening to the non test endpoint particularly, like I am doing, they will start getting beta data which can cause a lot of trouble. Hence my recommendation to bump the version.

**Pull request closed without merging**
