### PR TITLE
Allow an empty commodities array in commodities/3

### PR DESCRIPTION
**Pull request by lexi-lambda**
This makes the change proposed in #107.

### CODE REVIEW

**Comment by lexi-lambda** [comment]
@AnthorNet Gentle ping about this, as downstream support for this has officially been released in EDMC.

**Comment by AnthorNet** [comment]
Is every listener ok with this? No unintended side effects?

**Comment by lexi-lambda** [comment]
I thought about that, and I can’t say I’m enough of an expert on how all these pieces fit together to say for certain. But I *think* they ought to be, because it’s already possible to end up with a fleet carrier market with no commodities, since that would be the case the first time a fleet carrier’s information is sent to EDDN (and it is not currently buying or selling anything). Of course, you’d have a better understanding if that’s actually the same situation or not than I do.

**Comment by DarkMinded** [comment]
They should be, any list could be null or empty if the clients do not support this they should!

Cumprimentos,

Nuno Anjos

________________________________

**Pull request merged**
